### ISSUE TITLE
Navigation Buggy after Updating Livewire to 2.6.1

### ISSUE THREAD

**Issue by bomshteyn** [rappasoft/laravel-livewire-tables#457] opened 2021-09-14 23:12 UTC
The URL jumps back to previous page about a second after navigating between livewire pages while showing the correct content.

Downgrading to livewire 2.5.5 solves the issue. 

I narrowed it down to pages that are using Livewire Tables Package so i am guessing it's somehow related to it.

related discussion: https://github.com/livewire/livewire/discussions/3725

**Comment by cswni** [comment] 2021-09-15 05:58
Same situation.
Downgrading to livewire 2.5.5 solves the issue.

**Comment by rappasoft** [comment] 2021-09-15 12:58
[Looks like they fixed it](https://github.com/livewire/livewire/discussions/3725#discussioncomment-1332424)

**Comment by pktharindu** [comment] 2021-09-15 13:26
I can confirm this is now fixed with Livewire v2.6.2.

**Closed** 2021-09-15 14:16 UTC

**Comment by rizkhal** [comment] 2021-10-04 04:06
Hello, i think i have the similliar problem but only on production, see [here](https://github.com/livewire/livewire/discussions/3725#discussioncomment-1422629) for detail..

The version i use
```
  "livewire/livewire": "^2.5.5",
  "rappasoft/laravel-livewire-tables": "1.15.0",
```
