### ISSUE TITLE
[Bug]: The component class constructor doesn't seem to run when using ComponentColumn

### ISSUE THREAD

**Issue by nathan-io** [rappasoft/laravel-livewire-tables#1513] opened 2023-11-01 17:41 UTC
### What happened?

We're trying to use a Blade component as a column:

```
            ComponentColumn::make('Fine Content', 'fine_weight_ozt')
                ->component('weight-with-conversions')
                ->attributes(fn ($value, $row, Column $column) => [
                    'weight' => new Weight($row->weighing_unit_type, $row->fine_weight),
                ]),
```

This does cause livewire-tables to attempt to render the component view, but it throws an "Undefined variable" exception because the public properties that are set in the constructor aren't present. 

I don't believe the problem is in the component, because it works without issue when called in a view:

```
@php
     $weight = new App\Data\Weight(1, 1)
@endphp
<x-weight-with-conversions :weight="$weight" />
```

So perhaps the constructor is not firing? 

---

Here's the component class and view:

```
...
class WeightWithConversions extends Component
{
    public Weight $weight;
    public string $conversions;

    /**
     * Create a new component instance.
     */
    public function __construct(Weight $weight)
    {
        $this->weight = $weight;

        $this->conversions =
            $weight->toString(WeighingUnitType::TroyOunce) . '<br/>' .
            $weight->toString(WeighingUnitType::Gram) . '<br>' .
            $weight->toString(WeighingUnitType::Pennyweight);
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.weight-with-conversions');
    }
}
```

View:

```
<button data-popover data-tippy-content="{!! $conversions !!}" class="underline-dotted">
    {{ $weight->toString() }}
</button>
```

### Package Version

3.1.0

### PHP Version

8.1.x

### Laravel Version

10

### Theme

None

**Comment by lrljoe** [comment] 2023-11-01 17:44
Thanks for raising, I'll have a look in a bit, just so I can confirm:
```
class WeightWithConversions extends Component
```

Is that:
Livewire\Component
or
Illuminate\View\Component

I'm assuming the latter?

**Comment by nathan-io** [comment] 2023-11-01 17:45
It's a Blade component.

```
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;
use App\Data\Weight;
use App\Enums\Item\WeighingUnitType;

class WeightWithConversions extends Component
{
    public Weight $weight;
    public string $conversions;

    /**
     * Create a new component instance.
     */
    public function __construct(Weight $weight)
    {
        $this->weight = $weight;

        $this->conversions =
            $weight->toString(WeighingUnitType::TroyOunce) . '<br/>' .
            $weight->toString(WeighingUnitType::Gram) . '<br>' .
            $weight->toString(WeighingUnitType::Pennyweight);
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.weight-with-conversions');
    }
}
```

**Comment by lrljoe** [comment] 2023-11-01 17:46
Perfect, thanks, I'll take a look shortly.

**Comment by lrljoe** [comment] 2023-11-01 21:56
Just having a look at why this isn't working for you, as I have a ComponentColumn working in my test environment.  Will see if I can figure out why it works for me and not for you!

**Comment by nathan-io** [comment] 2023-11-01 22:07
Thanks for looking into this! 

I see one potential issue (weighing_unit_type has a cast), I'll investigate and update this.

**Comment by nathan-io** [comment] 2023-11-02 00:42
I looked at it, still no luck. The `Weight` constructor throws an exception if supplied invalid arguments. 

I put a `dd()` in the component constructor, but I don't get a dump. I move it to the view, and I do. 

Can you show me your working test?

**Comment by lrljoe** [comment] 2023-11-02 00:44
I'll have to share it tomorrow, as I'm tuckered out now: [See Here](https://github.com/rappasoft/laravel-livewire-tables/pull/1511) for why!  That should all get merged in, possibly tomorrow as a new release.  But then I will definitely share my working example!

**Comment by nathan-io** [comment] 2023-11-03 01:42
> Although glancing at it, I think mine may be an anonymous component, which would explain a lot as to why mine is working and yours isn't.

Yes I think this is the difference.

**Comment by nathan-io** [comment] 2023-11-17 20:36
Hi, wanted to see if you've had any chance to take a look at this. Thank you!

**Comment by nathan-io** [comment] 2023-12-17 22:33
Don't close :)

**Comment by nathan-io** [comment] 2024-02-23 17:23
.

**Comment by nathan-io** [comment] 2024-06-20 16:18
This is still an issue

**Comment by lrljoe** [comment] 2024-06-22 22:11
Apologies, stalebot gets a bit over-eager (I have no control over that!)

I'll do my best to take a look at this over the next week (so expect an update by the end of the month).

I have tinkered a little, and have got this resolved in my local environment (I've added a new Column type to avoid any conflicts with existing code).

If you want to give it a whirl, ping me on Discord and I'll let you know what to do to give it a test (would appreciate a real-world test tbh)

**Comment by lrljoe** [comment] 2024-07-03 22:29
Please do reach out if you want to test this, as otherwise I'll throw it into the next version, and it may not do what you want!

**Comment by nathan-io** [comment] 2024-07-04 13:51
Hello! I don't really use Discord. I did post the component class and view in my original comment, would you be able to test using that?

**Comment by nathan-io** [comment] 2024-07-04 13:52
Hello! I don't really use Discord, could you post some code here? I could temporarily modify my local vendor files and test it.

**Comment by nathan-io** [comment] 2024-07-04 13:54
To test this, all you need is a component which has a class constructor that sets some variable. Then reference that variable in the component view to make sure it's available.

**Comment by lrljoe** [comment] 2024-07-16 04:54
Okay, replicated, and have a fix for it, it'll come out as a new ViewComponentColumn type.

**Comment by lrljoe** [comment] 2024-07-16 05:01
I will need to write:
- Docs
- Tests

Before this can be released.  Estimate is by end of the month

Please do feel free to test in the meantime!

**Comment by lrljoe** [comment] 2024-07-20 00:31
There's a new ViewComponentColumn which fixes this issue.  Let me know if you have any issues.  Docs should be on the site shortly.

**Comment by lrljoe** [comment] 2024-07-24 04:08
Docs are released for ViewComponentColumn which should fix this!  Please reply if issue persists.

**Comment by nathan-io** [comment] 2024-07-25 14:42
Thank you! I'll try to test this weekend and let you know how it works.

**Comment by nathan-io** [comment] 2024-08-04 00:11
I was able to try this out but am still having trouble.

Here's the latest thing I've tried:

```
            ComponentColumn::make('Fine Content', 'fine_weight_ozt')
                ->component('weight-with-conversions')
                ->attributes(fn ($value, $row, Column $column) => [
                    'weight' => new Weight($row->weighing_unit_type->value, $row->fine_weight),
                ])
```

I've also tried `ViewComponentColumn` with the same result. The docs say to use `ComponentColumn`, but the actual class name is `ViewComponentColumn`.

When I use this, I get an exception: https://gyazo.com/de0a72a769ca3b0bab45ec97b2e2f417

It doesn't seem like the exception itself is meaningful, as the underlying issue is that for whatever reason, the `weight` property we're passing into this component column is used as the `$heading` value in a completely different Blade component that lives on the same view that we're calling the Livewire table from.

**Comment by lrljoe** [comment] 2024-08-04 00:38
@nathan-io  - Can you share your weight-with-conversions component if possible?

**Comment by nathan-io** [comment] 2024-08-04 01:24
I found a `dd()` I had left in the component class. I haven't worked on this in a few months so I totally forgot about that. 

Unfortunately that wasn't the issue, but it at least explains why it didn't matter if I used `ViewComponentColumn` or `ComponentColumn` (have to use the latter).

I'm now getting an `Undefined variable $conversions` exception in the component view `weight-with-conversions.blade.php`.

`$conversions` is a public property set in the component class `WeightWithConversions`, so it should be available there.

When I tried `{!! $conversions ?? '' !!}`, the exception changed to `Undefined variable $weight`.

`$weight` is another public property set in the component class. 

The component works fine when we just call it like:

```
<x-weight-with-conversions :weight="$itemWeight"/>
```

So to test, you probably don't need `App\Data\Weight` or `App\Enums\Item\WeighingUnitType`. You can just set the properties to some arbitrary value, as I think the real issue is that the component class still isn't firing. 

### Usage 

package v3.3.4

```
            ComponentColumn::make('Fine Content', 'fine_weight_ozt')
                ->component('weight-with-conversions')
                ->attributes(fn ($value, $row, Column $column) => [
                    'weight' => new Weight($row->weighing_unit_type->value, $row->fine_weight),
                    // 'conversions' => '' // The constructor should set this for us but still got `Undefined variable $conversions` when including this as an experiment
                ])->sortable(
                    fn(Builder $query, string $direction) => $query->orderBy('fine_weight_ozt', $direction)
                ),
```


### Component class

```
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;
use App\Data\Weight;
use App\Enums\Item\WeighingUnitType;

class WeightWithConversions extends Component
{
    public Weight $weight;
    public string $conversions;

    /**
     * Create a new component instance.
     */
    public function __construct(Weight $weight)
    {
        $this->weight = $weight;

        $this->conversions =
            $weight->toString(WeighingUnitType::TroyOunce) . '<br/>' .
            $weight->toString(WeighingUnitType::Gram) . '<br>' .
            $weight->toString(WeighingUnitType::Pennyweight);
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.weight-with-conversions');
    }
}
```

### The component view

```
<button data-popover data-tippy-content="{!! $conversions !!}" class="underline-dotted">
    {{ $weight->toString() }}
</button>
```

**Comment by lrljoe** [comment] 2024-08-04 03:01
Hmmm, do all of your rows have both $row->weighing_unit_type->value and $row->fine_weight

Otherwise you may not be able to create a Weight, which may result in the error you're experiencing, not saying that's definitely the issue, but possible

**Comment by nathan-io** [comment] 2024-08-04 03:08
Unfortunately that's not the issue. `weighing_unit_type` and `fine_weight` aren't nullable. All of the values for both columns are validated during seeding.

**Comment by lrljoe** [comment] 2024-08-04 03:14
I think I may have just figured out why, just testing to see if it's the case!

**Comment by lrljoe** [comment] 2024-08-04 04:00
So my test column looks like this, just using notes_count as it's a value I already have in a test table.

```php
            ViewComponentColumn::make('Weight', 'name')
            ->component('test-weight')
            ->attributes(fn ($value, $row, Column $column) => [
                'weight' => new Weight(($row->notes_count ?? 10)*rand(5,240))
            ]),
```

**test-weight View Component**
```php
<?php

namespace App\View\Components;

class TestWeight extends \Illuminate\View\Component
{
    public ?\App\Weight $weight;

    public function __construct(\App\Weight $weight)
    {
        $this->weight = $weight;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): \Illuminate\Contracts\View\View|Closure|string
    {
        return view('test-weight');
    }

}
```

**test-weight.blade.php**
```blade
<div>
    {{ $weight->getConversion() ?? 'Unknown'}}
</div>
```


**Weight Class**
```php
<?php

namespace App;

class Weight
{
    public int $grams;
    public int $ounces;

    public function __construct(int $grams)
    {
        $this->grams = $grams;
        $this->setOunces();
    }

    public function setOunces()
    {
        $this->ounces = $this->grams / 28.3495;
    }

    public function getConversion(): string
    {
        return $this->grams."g, ".$this->ounces."oz";
    }
}
```

It seems to be working:
![image](https://github.com/user-attachments/assets/ab697461-e81f-4897-b7a5-9a3382a803a5)

**Comment by lrljoe** [comment] 2024-08-04 04:07
3.4.0 is out now

This fix will be in 3.4.1 which I'll release momentarily

**Comment by lrljoe** [comment] 2024-08-04 04:10
v3.4.1 is out, ViewComponentColumn is the one you want to use, as this has the fix in.

**Comment by nathan-io** [comment] 2024-08-04 12:33
Thank you. I upgraded to 3.4.2. I'm getting a different exception now: https://gyazo.com/caed47af06a1744f22e76b8306ce7d14

### Usage

```
            ViewComponentColumn::make('Fine Content', 'fine_weight_ozt')
                ->component('weight-with-conversions')
                ->attributes(fn ($value, $row, Column $column) => [
                    'weight' => new Weight($row->weighing_unit_type->value, $row->fine_weight),
                ]),
```

**Comment by lrljoe** [comment] 2024-08-04 12:52
Just to make sure I can replicate it, whats the namespace for your WeightWithConversions component?

**Comment by nathan-io** [comment] 2024-08-04 13:17
It's `App\View\Components`

**Comment by lrljoe** [comment] 2024-08-04 14:16
So I've been able to replicate the issue, and managed to get it working how it should, I now just need to figure out how to implement it properly.

**Comment by lrljoe** [comment] 2024-08-04 14:41
Aand, I have a working solution.  If you're around today, and fancy giving it a test, I'll create a temporary branch for it, as I'll need update tests/docs etc

**Comment by lrljoe** [comment] 2024-08-04 15:07
It's in the development branch at the mo, I've added a new method called customComponent that expects the actual View Component Class to be specified.

This then works as expected (seems to at least so far in my testing!)

```
            ViewComponentColumn::make('Weight', 'name')
            ->customComponent(\App\View\Components\TestWeight::class)
            ->attributes(fn ($value, $row, Column $column) => [
                'weight' => new Weight(($row->notes_count ?? 10)*rand(5,240))
            ]),
```

**Comment by nathan-io** [comment] 2024-08-04 17:53
When I switch to branch `dev-develop` (98a5ef3), the `ViewComponentColumn` can't be found.

I'll be happy to test this once you've been able to test and release it.

**Comment by lrljoe** [comment] 2024-08-04 19:24
@nathan-io  - Sorry, the active development branch is:

dev-development 

It's looking likely the back end of next week to make it into a release, as there's a fair few tests to write to cater for the different permutations, including adding in some weird/whacky View Components to make sure it operates consistently.  Seems to so far tho!

**Comment by lrljoe** [comment] 2024-08-08 03:01
@nathan-io  - v3.4.3 is out with the fixes in

### customComponent

Should you wish to render the Custom Component in it's entirety, then you may use the customComponent method.  Otherwise it will pass in the values directly to the blade, rather than executing your View Component.

```php
ViewComponentColumn::make('Weight', 'grams')
    ->customComponent(\App\View\Components\TestWeight::class)
    ->attributes(fn ($value, $row, Column $column) => [
        'weight' => new Weight($value),
    ]),
```

**Comment by nathan-io** [comment] 2024-08-08 12:14
Unfortunately the issue persists with 3.4.3.

```
            ViewComponentColumn::make('Fine Content', 'fine_weight_ozt')
                ->customComponent(WeightWithConversions::class)
                ->attributes(fn ($value, $row, Column $column) => [
                    'weight' => new Weight($row->weighing_unit_type->value, $row->fine_weight),
                ]),
```

Result: https://gyazo.com/50dbdc870f5703cbc9612eb8e91d5dd2

**Comment by lrljoe** [comment] 2024-08-10 07:13
In your blade for the component, try
```
$this->conversions
```
instead of
```
$conversions
```

**Comment by nathan-io** [comment] 2024-08-10 14:36
I did try `$this->conversions` and got exception "Property [$conversions] not found on component: [retail-catalog-item-table]".

However, that isn't the correct way to access the variable from the view component. See https://laravel.com/docs/11.x/blade#passing-data-to-components:

> You should define all of the component's data attributes in its class constructor. All public properties on a component will automatically be made available to the component's view. It is not necessary to pass the data to the view from the component's render method:
> ...
> When your component is rendered, you may display the contents of your component's public variables by echoing the variables by name:

```
<div class="alert alert-{{ $type }}">
    {{ $message }}
</div>
```

While reviewing the docs, I noticed that my syntax was a bit different. So I refactored to this:

```
class WeightWithConversions extends Component
{
    public function __construct(
        public Weight $weight,
        public string $conversions = ''
    )
    {
        $this->conversions =
            $weight->toString(WeighingUnitType::TroyOunce) . '<br/>' .
            $weight->toString(WeighingUnitType::Gram) . '<br>' .
            $weight->toString(WeighingUnitType::Pennyweight);
    }

    public function render(): View|Closure|string
    {
        return view('components.weight-with-conversions');
    }
}
```

This works exactly the same as my previous implementation - it's fine when called like `<x-weight-with-conversions :weight="$weight"/>` within a Blade view: https://i.gyazo.com/a968845f7632fe8f2c994a1a8abb0818.png

However, when using this in the table column, I still get the "Undefined variable $conversions" exception in the component view. 

```
            ViewComponentColumn::make('Fine Content', 'fine_weight_ozt')
                ->customComponent(WeightWithConversions::class)
                ->attributes(fn ($value, $row, Column $column) => [
                    'weight' => new Weight($row->weighing_unit_type->value, $row->fine_weight),
                ]),
```

Do you have an example component class and view that you were able to get working with this? If so, I can try it out.

**Comment by lrljoe** [comment] 2024-08-14 06:53
I will put together an example later today, and triple check that it is working as it should

**Comment by lrljoe** [comment] 2024-08-16 06:11
So after mucking around for quite a while, the methods within construct() aren't being fired, that's applying both internally to the table, and externally.

The way I've got it working is:

```php
            ViewComponentColumn::make('Test','amount')
            ->customComponent(\App\View\Components\TestWeight::class)
            ->attributes(fn ($value, $row, Column $column) => [
                'weight' => new \App\Weight($row->amount),
            ]),
```

```php
<?php

namespace App\View\Components;

class TestWeight extends \Illuminate\View\Component
{
    public ?\App\Weight $weight;

    public function __construct(\App\Weight $weight)
    {
        $this->weight = $weight;
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): \Illuminate\Contracts\View\View|Closure|string
    {
        return view('test-weight')->with(['conversions' => $this->weight->getConversion()]);
    }

}```

Then test-weight.blade.php
```html
    <div>
        {{ $conversions }}
    </div>
```

**Comment by nathan-io** [comment] 2024-08-18 23:45
Thank you for the follow up and all of your efforts in this. 

> Not ideal, but not sure why it's not firing subsequent code within construct as of yet, I'm assuming it's something I'm missing in terms of Reflections

Yes I've always suspected that the constructor was either not firing at all, or somehow the data wasn't making it to the view the way it normally would when we call the component within a standard Blade context.

With that in mind, I tried a workaround that I honestly should've though of from the beginning:

```
Column::make('Fine Content', 'fine_weight_ozt')
    ->format(fn($value, $row, Column $column) => Blade::render('<x-weight-with-conversions :weight="$weight"/>', 
        ['weight' => new Weight($row->weighing_unit_type->value, $row->fine_weight)])
    )
    ->html(),
```

Result: [(screenshot)](https://gyazo.com/9f3250b0357907d785c48b29b787554c)

It also works using `view()`, I just didn't want to create another file.

```
Column::make('Fine Content', 'fine_weight_ozt')
    ->format(
        fn($value, $row, Column $column) => view('weight-with-conversions-container')->with([
            'weight' => new Weight($row->weighing_unit_type->value, $row->fine_weight)
        ])
    ),
```

Someone could use this approach to use Blade components or Livewire components (which may suffer from the same or similar issue) as columns without having to touch the component class or view.

The only issue I've noticed is that when I paginate, the links stop toggling the tippy popup. I'm such that's just some state thing.

**Comment by lrljoe** [comment] 2024-08-21 20:19
I'm assuming you're using bootstrap?

**Comment by nathan-io** [comment] 2024-08-21 23:39
Tailwind

**Comment by nathan-io** [comment] 2024-08-21 23:40
Tailwind

**Comment by lrljoe** [comment] 2024-08-21 23:42
In that case, 100% look at the native AlpineJS anchor approach

[https://alpinejs.dev/plugins/anchor](https://alpinejs.dev/plugins/anchor)

Most of the 3rd party popover/popper packages only run on first load, and setup instances for any element with "xyz" attributes.

**Comment by nathan-io** [comment] 2024-08-22 13:05
Thanks, I'll check that out!

As far as this issue, I wonder if `ViewComponentColumn` could be simplified based on this approach?

Instead of passing in a class name or arguments, you just pass in a string with the Blade to render, and the values for any props you're passing. In this case for example:

```
ViewComponentColumn::make('Fine Content', 'fine_weight_ozt')
    ->bladeComponentTag('<x-weight-with-conversions :weight="$weight"/>')
    ->attributes(fn ($value, $row, Column $column) => [
        'weight' => new Weight($row->weighing_unit_type->value, $row->fine_weight),
    ]),
```

Then in `ViewComponentColumn`  you could replace:

```
        if ($this->hasCustomComponent()) {
            $reflectionClass = new ReflectionClass($this->getCustomComponent());

            $reflectionInstance = $reflectionClass->newInstanceArgs($attributes);

            return $reflectionInstance->render();
        } else {
            return view($this->getComponentView())->with($attributes);
        }
```

with something like:

```
return Blade::render($bladeComponentTag, $attributes);
```

Not sure passing a Blade component tag rather than a class name feels 100% right, but at least it would** bypass the issue with the constructor.

**I think? maybe there's something special about doing it within a closure passed to `Column::format()`

**Comment by lrljoe** [comment] 2024-08-24 00:49
@nathan-io 

With fresh eyes, and considering what you shared, the simplest approach would really be:

A Column that uses a Custom View "test-weight-column", that recieves "$weight" which is an App\Weight::class object.:
```
            Column::make('NewWeight', 'amount')
            ->format(
                fn($value, $row, Column $column) => view('test-weight-custom-column-view')->withWeight(new \App\Weight($row->amount))
            ),
```

The custom view "test-weight-custom-column-view"

i.e. _resources/views/test-weight-custom-column-view.blade.php_ would look like:
```
<div>
    <x-test-weight :$weight />
</div>
```

This will then instantiate and call the "Test Weight" view Component:
```
namespace App\View\Components;

class TestWeight extends \Illuminate\View\Component
{
    public ?\App\Weight $weight;

    public $conversions;

    public function __construct(\App\Weight $weight)
    {
        $this->weight = $weight;
        $this->conversions = $weight->getConversion();
    }

    public function render(): \Illuminate\Contracts\View\View|Closure|string
    {
        return view('test-weight-123');
    }
}
```

Then the "test-weight-123" blade contains:
```
<div>
        {{ $conversions }}
</div>
```

**Comment by lrljoe** [comment] 2024-08-24 01:00
@nathan-io 

So I've simplified this somewhat:
```
            Column::make('TwstWe', 'amount')
            ->format(
                fn($value, $row, Column $column) => Blade::render('test-weight-custom-column-view', ['weight' => new \App\Weight($row->amount)])
            )->html(),
```

Where "test-weight-custom-column-view.blade.php" contains

```
<div>
    <x-test-weight :$weight />
</div>
```

**Comment by lrljoe** [comment] 2024-08-27 08:05
> Thanks, I'll check that out!
> 
> As far as this issue, I wonder if `ViewComponentColumn` could be simplified based on this approach?
> 

Yep, I'll certainly look at options for simplifying it based on the approach I highlighted above.  It won't be in the next 2 versions, but may be in a subsequent one.

**Closed** 2024-11-09 01:13 UTC
Labels: enhancement, wontfix
