### ISSUE TITLE
Issu with $model

### ISSUE THREAD

**Issue by fazriairmas** [rappasoft/laravel-livewire-tables#113] opened 2021-01-21 10:11 UTC
Issu with $model

help me,
I'm having a problem with the latest livewire. (Call to undefined method Closure :: isEmpty ())

**Comment by fazriairmas** [comment] 2021-01-21 10:13
Error
Call to undefined method Closure::isEmpty() (View: ....resources\views\vendor\laravel-livewire-tables\bootstrap-4\table-component.blade.php)

`     @if($models->isEmpty())

                    @include('laravel-livewire-tables::'.config('laravel-livewire-tables.theme').'.includes.empty')

                @else

                    @include('laravel-livewire-tables::'.config('laravel-livewire-tables.theme').'.includes.data')

                @endif`

**Comment by Geovanek** [comment] 2021-01-21 14:42
I have the same error.
I run again composer update and working.

**Comment by RJFares** [comment] 2021-01-21 15:41
This is a duplicate of the issue I posted and resolved, kindly check 
https://github.com/rappasoft/laravel-livewire-tables/issues/112

The issue is resolved by livewire which reverted the breaking changes in version 2.3.8

@Geovanek You were lucky :) your update came exactly after the livewire update

**Closed** 2021-04-14 20:09 UTC
