### ISSUE TITLE
Icon for toggle row content on mobile becomes out of sync after calling refreshDatatable

### ISSUE THREAD

**Issue by howdu** [rappasoft/laravel-livewire-tables#923] opened 2022-09-19 22:13 UTC
The hiding of row content works apart from the icon doesn't reset when calling 'refreshDatatable'.

**Comment by lrljoe** [comment] 2023-03-30 22:43
Just so I'm clear on this issue. Can you let me know the theme you're using.

Also please can you confirm my understanding that you're using a collapseOnMobile/Tablet column. And the icon isn't reflecting the display state after a refresh?

E.g. you apply a filter/sort and the icon remains open when it's not expanded, or icon shows closed when it's expanded.

I've moved a couple of other items into alpinejs approach, think this one may also need it.

**Comment by howdu** [comment] 2023-03-31 11:45
@lrljoe here's a quick video to demo the issue. 
https://user-images.githubusercontent.com/533658/229111269-441e01ff-f7ad-4c78-8262-e0327c53ed2e.mov

The table components has:
```php
protected $listeners = [
        'refreshVideos' => 'refresh',
];

public function refresh()
{
    $this->clearSelected();
    $this->emit('refreshDatatable');
}
```

After saving the modal I emit:
```php
$this->emit('refreshVideos');
```

**Comment by lrljoe** [comment] 2023-03-31 23:40
Thanks for the video, it helped identify where the issue is coming from.

I've written a quick fix for this which I'll need to go through and test more thoroughly.  It's effectively a complete revision of how the collapsed columns row works, so it'll need a fair chunk of testing.

Expect this not in the next release, but the one after!

**Comment by lrljoe** [comment] 2023-04-01 01:52
Fix does seem stable, but needs some tests writing, and some docs, so almost certainly not in this release, which I'm planning to wrap up tomorrow for pulling into master before I end up with 30 lines in the changelog.

I do have a few items queued up, so there's potential for it being ready in a couple of weeks.

To explain what needed doing to fix it:
I've replaced the current approach to toggling the row completely.
This removes the requirement to dispatch events within the browser, and uses AlpineJS instead.  The icon/row display updates instantly 

There's  also some replacing of wire keys that were linked to Row Indexes in some places with the primary key of the row, to avoid Livewire getting confused about what has changed.

For reference, I have also added in a method to allow for the table to remember which rows are expanded after filtering/browsing pages, which will be configurable via the configure () method, this uses a public array to store the Primary Key or the expanded items.  Disabled by default.

**Comment by lrljoe** [comment] 2023-04-17 02:36
Currently re-reviewing this fix, with potential to implement in 2.13

**Comment by lrljoe** [comment] 2023-05-08 22:12
It'll be in 2.14, as I've had to do a drains up and rewrite the collapsing function

**Comment by lrljoe** [comment] 2023-05-19 02:04
2.14 came out as an urgent one, so 2.15 it shall be!

**Closed** 2023-06-26 22:30 UTC
Labels: bug, wontfix, In Progress, Version 2
